### ISSUE TITLE
SelectCommand not implemented

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-commands-v2#14]
Should look at either a pure python implementation or wrap it. It was a template if I remember correctly.

**Comment by mrguisamuel** [comment]
Is it necessary to add the SelectCommand class first in [WPILib C++](https://github.com/wpilibsuite/allwpilib/tree/main/wpilibNewCommands/src/main/native/cpp/frc2/command)?

**Comment by auscompgeek** [comment]
@mrguisamuel it already exists in C++. https://github.com/wpilibsuite/allwpilib/blob/main/wpilibNewCommands/src/main/native/include/frc2/command/SelectCommand.h

**Comment by mrguisamuel** [comment]
For work, is it necessary the `.cpp` file or only the header?
Because the WPILibC++ doesn't have the [SelectCommand](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibcExamples/src/main/cpp/examples/SelectCommand/cpp/RobotContainer.cpp) example in complete form, as Java (I guess)

**Comment by auscompgeek** [comment]
I'm not sure I understand. The [C++ SelectCommand example](https://github.com/wpilibsuite/allwpilib/tree/main/wpilibcExamples/src/main/cpp/examples/SelectCommand) looks to be as complete as the [corresponding Java example](https://github.com/wpilibsuite/allwpilib/tree/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/selectcommand) to me.

**Comment by mrguisamuel** [comment]
woops, my mistake... I got confused here. Sorry for this @auscompgeek 😔

I wanna convert the `SelectCommand` example to python, this is why I questioned.
